[versions]
agp = "8.13.2"
kotlin = "2.3.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.3"
constraintlayout = "2.2.1"
jetbrainsKotlinJvm = "2.3.10"
kapt = "2.3.10"
dagger = "2.59.1"
inject = "1"
navigationSafeArgsGradlePlugin = "2.9.7"
viewmodel = "2.10.0"
fragment-ktx = "1.8.9"
navigation = "2.9.7"
room_version = "2.8.4"
flexbox_version = "3.0.0"
hilt_version = "2.44"

[libraries]

#Dagger
inject = { group = "javax.inject", name = "javax.inject", version.ref = "inject"}
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger"}
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger"}

#ViewModel
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "viewmodel"}
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "viewmodel"}
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx"}

#Navigation
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

#Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room_version"}
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room_version"}
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room_version"}

#Flexbox
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox_version" }

#Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt_version"}
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt_version"}

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgsGradlePlugin" }


[plugins]
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt_version" }
kapt = {id = "org.jetbrains.kotlin.kapt", version.ref="kapt"}
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.2.0" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
android-library = { id = "com.android.library", version.ref = "agp" }

